// Generated by CoffeeScript 1.8.0
var bus, most, setImmediate;

most = require('most');

if (typeof setImmediate === "undefined" || setImmediate === null) {
  setImmediate = function(f) {
    return setTimeout(f, 0);
  };
}

bus = function(initial) {
  var b$, _add, _end, _error;
  _add = _end = _error = null;
  b$ = most.create(function(add, end, error) {
    _add = add;
    _end = end;
    return _error = error;
  });
  b$.push = function(v) {
    return setImmediate(function() {
      return typeof _add === "function" ? _add(v) : void 0;
    });
  };
  b$.end = function() {
    return setImmediate(function() {
      return typeof _end === "function" ? _end() : void 0;
    });
  };
  b$.error = function(e) {
    return setImmediate(function() {
      return typeof _error === "function" ? _error(e) : void 0;
    });
  };
  b$.plug = function(v$) {
    var w$;
    w$ = bus();
    v$.forEach(w$.push);
    w$.forEach(b$.push);
    return w$.end;
  };
  if (initial != null) {
    b$.push(initial);
  }
  return b$;
};

module.exports = bus;
