// Generated by CoffeeScript 1.8.0
var R, bus, bus$, even$, hello$, log, most, odd$, unplug_hello;

most = require('most');

bus = require('most-bus');

R = require('ramda');

log = function(t) {
  return function(v) {
    return console.log(t, v);
  };
};

bus$ = bus();

bus$.forEach(log('bus$ ->'));

odd$ = most.from([1, 3, 5]).delay(50);

even$ = most.from([4, 6, 8]).delay(100);

hello$ = most.periodic(400, 'hello');

bus$.plug(odd$);

bus$.plug(even$);

unplug_hello = bus$.plug(hello$);

setTimeout(unplug_hello, 900);

setTimeout((function() {
  return bus$.push('something');
}), 500);

bus$.filter(isFinite).forEach(log('n ='));
